#!/usr/bin/node
'use strict';
const yargs = require('yargs');
const errors = require('./lib/errors');

const result = yargs.commandDir('commands')
  .demandCommand()
  .help()
  .argv;

if (typeof result._getResult === 'function') {
  result._getResult(result)
    .then((msg) => console.log(msg))
    .catch(err => {
      if (err instanceof errors.GogsCliError) {
        console.error(err.message);
        process.exit(err.exitCode || 1);
      } else {
        console.error(err);
        process.exit(1);
      }
    });
}
